### ISSUE TITLE
50 points bonus click

### ISSUE THREAD

**Issue by Stadtguerilla** [xinitrc-dev/twitch-points-autoclicker#1]
Can you please add the 50 points bonus click

**Comment by xinitrc-dev** [comment]
Hey! Could you elaborate on what you mean by that? The extension should auto click however many points appear in the bonus chest, is there another clickable bonus I'm missing?

**Comment by Stadtguerilla** [comment]
I mean "special bonuses +50"https://imgur.com/ZfLrTgk I think the name of this is ".tw-interactive"
but I'm too stupid to add it XD
but I tested it on normal side and with"alternate player for twitch.tv" Unfortunately, 50+ does not work for both

I like your addon because it works with "alternate player for twitch.tv"

**Comment by Stadtguerilla** [comment]
the 50+ just do not work with the addone "alternate player for twitch.tv" 
can you make it work together with the addons
the 10+ works with the "alternate player for twitch.tv"

**Comment by xinitrc-dev** [comment]
10+ points are passively granted to users, there is no need to click those, however 50+ are, and that's what this extension does.
However, (and this has been requested before) this will never work for an alternative player extension, and here's why: alternative player extension instead of opening webpage from Twitch.tv website, creates its own local page, taking video stream from twitch, as well as the chat. As such, the webpage you are landed at isn't twitch.tv/somethingsomething it's actually a local file created by and extension. Extension API (stuff we use to make extensions work) does NOT interact with any other extension pages other than your own, so I cannot possibly inject my own script into "alternate player"'s page. This was quite an unfortunate revelation to me as well, but I have found 0 possibilities to make it work, other than adding the auto-clicking feature directly to the "alternate player" code, which (duh, im not the owner) I cannot do :)

**Comment by xinitrc-dev** [comment]
Closing this issue, the reason described above.
