### ISSUE TITLE
Stoped working on 9/15/20 - was there a change to twitch or just me?

### ISSUE THREAD

**Issue by zackaryk1** [xinitrc-dev/twitch-points-autoclicker#12]
Stoped working on 9/15/20 - was there a change to twitch or just me? Not working after reloading add on too. Twitch might have changed something.?

**Comment by xinitrc-dev** [comment]
What browser are you using? Also do you see any errors in the console? I've added a buncha logging, so you should see stuff like:
```
 Twitch Points Autoclicker: Initialized! twitch-clicker.js:123:11
 Detected inside of a channel page. twitch-clicker.js:105:11
 Element detected. twitch-clicker.js:19:10
 Twitch Points Autoclicker: Clicked! twitch-clicker.js:32:12```

**Comment by zackaryk1** [comment]
Thanks for the reply. I use firefox. How do I access the console? I'll check again later today. It seemed odd.

**Comment by xinitrc-dev** [comment]
Press F12, then navigate to "console" tab in the newly opened window. In there you can type "clicker" in the filter output, so that you will only see messages from the extension. Screenshot attached
![firefox_2020-09-16_14-34-16](https://user-images.githubusercontent.com/14354528/93377937-b8714500-f829-11ea-8168-eef9c09fd715.png)

**Comment by zackaryk1** [comment]
It looks like its working - i'm getting clicked messages must of been a fluke - thanks and sorry for the trouble.
