### ISSUE TITLE
Twitch layout appears to have changed

### ISSUE THREAD

**Issue by noxora** [xinitrc-dev/twitch-points-autoclicker#15]
Hi there! Just a heads up that the twitch layout for this may have changed, as I don't see the add-on working as normal

**Comment by xinitrc-dev** [comment]
Hey! Just tested it and it works fine on my end! Please, refresh the page and see if you can spot any errors or if the extension is reporting as usual. You should be able to see something like:
"Elemnt detected."
"Twitch Points Autoclicker: Clicked!"

**Comment by noxora** [comment]
Hi There! 

I took a peek at my console and saw this, not sure what's going on with it

![image](https://user-images.githubusercontent.com/14023728/104406971-3d454480-5526-11eb-8c69-908e3ceb1c50.png)

**Comment by noxora** [comment]
I also saw this, missed it in the first snip 
![image](https://user-images.githubusercontent.com/14023728/104407416-2b17d600-5527-11eb-9f8e-d0d04b006b20.png)

**Comment by xinitrc-dev** [comment]
huh, good catch! will investigate tomorrow. thank you!

**Comment by xinitrc-dev** [comment]
Alrighty, so the error about 'postMessage' isn't relevant here, since it's not used in the extension. It seems like an error from twitch's internal extensions (the ones embedded in videos) since they also reference ext-twitch.tv which is twitch's domain that deals with them.
The issue, however, is that the webpage doesnt detect you being on a channel page, particularly, with this line failing: `document.body.contains(document.getElementsByClassName('community-points-summary')[0])`
Im honestly confused why it would fail since this check is already executed after waiting for 10 whole seconds, see https://github.com/xinitrc-dev/twitch-points-autoclicker/blob/143b3941ea366ac2e3e8d21dd4caf3fd2cb3813b/src/twitch-clicker.js#L122
One thing I could try is adding more checks that would wait 10 more seconds each, as it seems to be connected with the page load times

**Comment by xinitrc-dev** [comment]
Alrighty, I think the problem wasnt actually in the code shown above but rather in background.js part where it detects you going in and out of the stream page to relaunch the main script. I have updated that using a different event that seems way more robust. This is pushed in 1.6 update, which will be uploaded to all the webstores shorty.

**Comment by noxora** [comment]
Thanks for the speedy work on this! You rock!
